---
title: "Data Cleaning and Preparation"
output: html_document
---


```{r}

# setup
library(tidyverse) # makes life easier
library(googlesheets4) # R interface to Google Sheets
library(geodist) # Compute distance between 2 coordinates



```

## Extracting the data

We download the data locally because it is not too large and it is good to have the data save somewhere else that only on the Google Drive.  

```{r}

# read the study plan:
study_plan <- googlesheets4::read_sheet(
  "https://docs.google.com/spreadsheets/d/1KCDf10VUDOEMKvIobbgmAJub0w1ETslf4oVmrzS8wQQ/edit#gid=0"
)
rio::export(study_plan, "../raw_data/study_plan.csv")

```


```{r}

# try to read all the sheets and save them as .csv
n_sheets_to_download = dim(study_plan)[1]
previous_city = "Nope!" # used to count number of sample by city
for (i in 1:n_sheets_to_download){
  current_sheet_link = study_plan[i,]$Link
  # print(current_sheet_link)
  # the .csv extracted are not saved as Google Sheets, but just csv
  # thus we cannot use googlesheets4 to read them.
  # we extract their Google ID
  current_sheet_link = stringr::str_replace(current_sheet_link, "https://drive.google.com/file/d/", "")
  current_google_id = stringr::str_replace(current_sheet_link, "/view\\?usp=sharing", "")
  # print(glue::glue("https://docs.google.com/uc?id={current_google_id}&export=download"))
  # then use it to get the csv
  # source of trick: https://stackoverflow.com/questions/33135060/read-csv-file-hosted-on-google-drive
  current_sheet <- rio::import(glue::glue("https://docs.google.com/uc?id={current_google_id}&export=download"),
                               format = "csv",
                               # sep = ", ",
                               # header = TRUE,
                               # class = "tibble",
                               skip = 9) %>% # skip the first useless rows
    select(`Your Rank`, Latitude, Longitude)
  # not sure why not working anymore... alternative: read.csv. seems to be auth issue (error 403)
  print("data extracted")
  
  # then download the result locally
  current_city = stringr::str_replace_all(study_plan[i,]$City, " ", "-" ) # add city in filename
  # we could also add the law firm, but probably not useful. 
  # We add a sample number by city:
  if (previous_city == current_city){
    n_sample = n_sample + 1
  } else {
    n_sample = 1
  }
  padded_n_sample = stringr::str_pad(as.character(n_sample), 2, side = "left", pad = "0") # consistent name, better ordering
  print(current_city, padded_n_sample)
  rio::export(current_sheet, glue::glue("../raw_data/scans/{current_city}_{padded_n_sample}.csv"))
  previous_city = current_city # re-initialize sample counter
}
```


## Reshape Data

We read all the .csv of the scans/samples, compute the distance to the center, and store everyting in long format in a single tidy tibble.  


```{r}

all_files <- list.files(path = "../raw_data/scans/")
counter = 1
all_samples_list = list()
for (file in all_files){
  sample_name = stringr::str_extract(file, '.*(?=\\.csv)')
  print(sample_name)
  sample = rio::import(glue::glue("../raw_data/scans/{sample_name}.csv"))
  origin_lat = sample[113,]$Latitude
  origin_lon = sample[113,]$Longitude
  origin_rank = case_when(
        sample[113,]$`Your Rank` == "20+" ~ 21,
        TRUE ~ as.numeric(as.character(sample[113,]$`Your Rank`))
      )
  # print(origin_rank)
  sample <- sample %>% 
    mutate(
      geodist = as.numeric(round(geodist::geodist_vec(Latitude, Longitude, origin_lat, origin_lon)/1000, 3)), # /1000 for km
      rank = case_when(
        `Your Rank` == "20+" ~ 21,
        TRUE ~ as.numeric(as.character(`Your Rank`))
      ),
      city_sample = sample_name
    ) %>%
    rowwise() %>%
    mutate(drop = rank - origin_rank) %>% # drop to the origin rank
    ungroup() %>%
    select(city_sample, drop, geodist, rank, Latitude, Longitude)
  print(paste("origin: ", origin_rank, " , rank: ", sample[113,]$rank, ", drop: ", sample[113,]$drop))
  
  all_samples_list[[counter]] <- sample
  counter = counter + 1
  
}

# we have all the samples in a list, now we need to combine them in a single tibble:
# (see https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402)
all_samples = do.call(rbind, all_samples_list) %>%
  separate(city_sample, into = c("City", "Sample"), sep = "_")

# we save a tidy tibble in long format with all the samples for the scans
# it should contain all what we need for the analyses.
rio::export(all_samples, "../proc_data/samples_10_10.csv")
rio::export(all_samples, "../proc_data/samples_10_10.rds")


```










